name: Bump Minor Version

on:
  push:
    branches:
      - main

jobs:
  bump-minor:
    name: Bump minor version (Poetry)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies (including dev)
        run: source $HOME/.cargo/env && uv sync --only-dev

      - name: Bump version
        id: bump_version
        run: |
          uv run --no-sync poetry version minor
          echo "VERSION=$(uv run --no-sync poetry version -s)" >> $GITHUB_OUTPUT

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add pyproject.toml
          git commit -m "ci: bump minor version to v${{ steps.bump_version.outputs.VERSION }} [skip ci]" || echo "No changes"
          git push origin HEAD:main
