name: Bump Minor Version

on:
  push:
    branches:
      - main

jobs:
  bump-minor:
    name: Bump minor version (Poetry)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies (including dev)
        run: source $HOME/.cargo/env && uv sync --only-dev
      - name: Bump version
        run: |
          poetry version minor
          echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add pyproject.toml
          git commit -m "ci: bump minor version to v${{ env.VERSION }} [skip ci]" || echo "No changes"
          git push origin HEAD:main
