name: Build

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_run:
    workflows:
      - Static Analysis
    types:
      - completed

jobs:
  build:
    if: >-
      (github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        (
          startsWith(github.event.workflow_run.head_branch, 'main') ||
          startsWith(github.event.workflow_run.head_branch, 'develop')
        )
      ) ||
      (github.event_name == 'pull_request' &&
        (
          github.event.pull_request.base.ref == 'main' ||
          github.event.pull_request.base.ref == 'develop'
        )
      )
    environment: staging
    name: Build FastMCP Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and only dev dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --only-dev

      - name: Extract version
        id: extract_version
        run: |
          echo "VERSION=$(uv run --no-sync poetry version -s)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build FastMCP image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: fastmcp
          push: false
          tags: |
            madmathematician971/mcp-it-tools:${{ steps.extract_version.outputs.VERSION }}
            madmathematician971/mcp-it-tools:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
