name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy_images:
    name: Deploy Docker Images
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: Checkout code at release tag
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.release.tag_name }}

        - name: Extract version
          id: extract_version
          run: |
            TAG_NAME="${{ github.event.release.tag_name }}"
            echo "VERSION=${TAG_NAME#v}" >> $GITHUB_OUTPUT

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push FastMCP image
          uses: docker/build-push-action@v5
          with:
            context: .
            target: fastmcp
            push: true
            tags: |
              madmathematician971/mcp-it-tools-fastmcp:latest
              madmathematician971/mcp-it-tools-fastmcp:${{ steps.extract_version.outputs.VERSION }}
